### ISSUE TITLE
Use of additional options

### ISSUE THREAD

**Issue by jERCle** [LotarProject/dokuwiki-plugin-datatables#10]
Page says 'See https://datatables.net/reference/option/ for complete options. ' although I was wondering how I would format the other options, such as 'search.search' within Dokuwiki as search.search="fred" will not work and generate data-search.search"fred" html

**Comment by ghybs** [comment]
Hi,

Actually you should transform your options into HTML5 attribute parameters (as mentioned here: https://datatables.net/manual/options#HTML-5-data-attributes), without the  `data-` prefix (it is added by DokuWiki DataTables plugin).

But even that page is not very clear. In fact, the values of your options can be JSON data, exactly like you could have done if initializing the DataTables library from JavaScript. So I guess in the case you mention, you would write `search='{"search":"fred"}'`.

Note that because your value must be valid JSON, the key and value strings `"search"` and `"fred"` must be wrapped with double quotes `"`, whereas the entire attribute value be wrapped with single quotes `'`.

But for this to be correctly used by DokuWiki DataTables plugin, you will have to modify it first, as explained in issue #7 .

I hope this will work for you.

**Comment by ghybs** [comment]
Hi again,

The plugin is now updated with modification described in #7 incorporated as pull request #9, so it should work by simply updating it through DokuWiki.

Please make sure to use the syntax above.

Hope this helps.

**Comment by jERCle** [comment]
Thank you for the information, greatly appreciated!

Regards,
Evan
