### ISSUE TITLE
Translation not enabled ?

### ISSUE THREAD

**Issue by blacklord049** [LotarProject/dokuwiki-plugin-datatables#19]
Hi,

I installed the datatables plugin on my Wiki (detritus release, PHP7), enabled "enableLocalization" setting, emptied the cache, but the texts are not translated (search box, showing x entries, etc).

My wiki is in french. 
Thank you

**Comment by Klap-in** [comment]
Javascript plugin translations was implemented for javascript stuff that was in the core of DokuWiki.
https://github.com/splitbrain/dokuwiki/pull/503
(original bug https://bugs.dokuwiki.org/index.php?do=details&task_id=2912)
DokuWiki does not yet provide a solution for other plugins, like the datatables plugin, that like to load translations.

**Comment by LotarProject** [comment]
Hi! I have tested with the lastest version and work. Can you send: 
  * the version of plugin
  * your locale

At your disposal,
Joseph

**Comment by blacklord049** [comment]
Works now , thank you !

**Comment by dralli72** [comment]
Hi! Sorry to answer here after almost 2 year since this issues has been closed, but I just realized that the "enableLocalization" option does not work with the "de-informal" locale. Translations should be the same as in "de" locale, but I think "de-informal" is not recognized by DataTables. Any idea how to solve that?

Thanks you!
