### ISSUE TITLE
Plugin works only on one page

### ISSUE THREAD

**Issue by mic-haf** [LotarProject/dokuwiki-plugin-datatables#27]
I recognised a strange problem. When I installed the datatables plugin, I used it on a page in the wiki successfully. After some weeks I tried to use the same syntax in another page. Unfortunately there are no changes visible to a normal table. If I copy the exact same table (with the tags <datatables>) into the page I used the plugin before it works. So in my dokuwiki there is only one existing page (I tried other) where the plugin is working.
If I generate new pages in my dokuwiki the plugin works there as well.
I tried to delete the cache (touching the local.php file over ftp) but it's still the same problem.
Any hints?

**Comment by mic-haf** [comment]
I could localize the problem. When I delete in the config section the pages for excluding the plugin it works again. Even though the excluding pages were not the ones the plugin didn't work. So maybe there is a little bug with this excluding configuration part.

**Comment by LotarProject** [comment]
👍 Thanks

**Comment by aubreyz** [comment]
I think this issue should be re-opened because I have the identical problem. 

Exactly the same page code works in some namespaces but not in others. 

As per the above, when I delete the default regex code in the configuration (so it is now blank) those pages magically work (at least for now) even though the regex has no relevance at all to the namespaces in question. The bug must lie here. 

With the default regular expression

This namespace does not work:

software:dokuwiki:datatables:simple

this one does

cliffordlodge:ross:events_log_ch
